.data
MY_SPEED            word ?
MY_SCORE            word ?
MY_MENU_COL         word ?
MY_DIFFICULTY       word ?
;-----------------------------------------
MY_FOOD_CNT         word ?
MY_FOOD_SP_BAR      word ?
;-----------------------------------------
MY_SNAKE_GETFOOD    word ?
;-----------------------------------------
MY_CHAR             byte ?
;-----------------------------------------
MY_SOUND_BACKGROUND byte "7895.wav",0
MY_SOUND_DEATH		byte "7896.wav",0
MY_SOUND_GROWTH		byte "7897.wav",0
MY_SOUND_BEGIN		byte "7898.wav",0
